version: "3.7"

services:
  
  flask:
    build: ./flask
    container_name: flask
    restart: always
    volumes: 
      - "./flask:/app"
    environment:
      FLASK_DEBUG: 1
      IN_CONTAINER: 1

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always 
    ports:
      - "80:80"
